[graph]
exclude-unpublished = true

[advisories]
unmaintained = "none"
yanked = "warn"

[licenses]
private = { ignore = true }
unused-allowed-license = "allow"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "OpenSSL",
    "Zlib",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
]

[bans]
multiple-versions = "allow"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
